WasteRecyclingSystem/urls.py
from django.urls import path, include, re_path

import xadmin
from django.views.static import serve

from WasteRecyclingSystem.settings import MEDIA_ROOT
from apps.user.views import IndexView, RegisterView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("xadmin/", xadmin.site.urls),
    path("captcha/", include('captcha.urls')),

    # media
    re_path(r'^media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT }),

    # 首页
    path('', IndexView.as_view()),
    path('index/', IndexView.as_view(), name="index"),

    # user app
    path('user/', include('user.urls', namespace='user')),

    # order app
    path('order/', include('order.urls', namespace='order')),

    # scrap app
    path('scrap/', include('scrap.urls', namespace='scrap')),

]

# 配置全局404变量
handler404 = 'user.views.page_not_found'
# 配置全局500变量
# handler500 = 'user.views.page_error'

apps/order/urls.py
# -*- coding: utf-8 -*-
# @DATE    : 2019/4/18 
# @Author  : licg
# @Email   : licgbeyond@foxmail.com

from django.urls import path

from apps.order.views import OrderListView, OrderEditView, OrderSubmitView, OrderCreateView

app_name = 'order'

urlpatterns = [
    path('list/', OrderListView.as_view(), name='order_list'),

    # 完善订单信息
    path('edit/', OrderEditView.as_view(), name='order_edit'),

    # 提交订单
    path('submit/<order_num>', OrderSubmitView.as_view(), name='order_submit'),

    # 用户下单
    path('create/', OrderCreateView.as_view(), name='order_create'),
]

apps/scrap/urls.py
# -*- coding: utf-8 -*-
# @DATE    : 2019/4/13 
# @Author  : licg
# @Email   : licgbeyond@foxmail.com
from django.urls import path

from apps.scrap.views import ScrapListView

app_name = 'scrap'

urlpatterns = [
    path('list/', ScrapListView.as_view(), name='scrap_list'),
]

apps/user/urls.py
# -*- coding: utf-8 -*-
# @DATE    : 2019/3/31 
# @Author  : licg
# @Email   : licgbeyond@foxmail.com
from django.urls import path

from user.views import *

app_name = 'user'

urlpatterns = [
    # 注册
    path('register/', RegisterView.as_view(), name='register'),

    # 登录
    path('login/', UserLoginView.as_view(), name='login'),

    # 个人信息
    path('info/', UserProfileView.as_view(), name='info'),

    # 修改信息
    # path('<int:user_id>/modify/', UserProfileModifyView.as_view(), name='UserProfileModify'),

    # 发送手机验证码（修改手机号）
    path('send_phone_code/', SendPhoneVerifyCode.as_view(), name='send_phone_code'),

    # 发送手机验证码（修改支付宝）
    path('send_account_code/', SendAccountVerifyCode.as_view(), name='send_account_code'),

    # 修改手机号
    path('update_phone/', UpdatePhone.as_view(), name='update_phone'),

    # 修改支付宝账号
    path('update_account/', UpdateAccount.as_view(), name='update_account'),

    # 修改密码
    path('update/pwd/', UpdatePwdView.as_view(), name='update_pwd'),

    # 用户退出
    path('logout/', LogoutView.as_view(), name='logout'),

]

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>    {% block titile %}首页 | {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %} {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
</head>
<body>
<section class="headerwrap ">
    <header>
        <div class=" header">
            <div class="top">
                {% if request.user.is_authenticated %}
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>23333333</b></p></div>
                        <div class="personal">

                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/>
                                </dd>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dd>
                                        <h2>{{ user.nick_name }}</h2>
                                        <p>{{ user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'scrap:scrap_list' %}">废品列表</a>
                                    <a class="fr" href="{% url 'user:info' %}">主页</a>
                                    <a class="personcenter fl" href="{% url 'order:order_list' %}">订单列表</a>
                                    <a class="fr" href="{% url 'user:logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'user:login' %}">
                            <div class="msg-num"><span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                        </a>
                    </div>
                {% else %}
                    <div class="wp">
                        <div class="fl"><p>服务电话：<b>23333333</b></p></div>
                        <!--登录后跳转-->


                        <a style="color:white" class="fr registerbtn" href="{% url "user:register" %}">注册</a>
                        <a style="color:white" class="fr loginbtn"
                           href="{% url 'user:login' %}?next={{ request.path }}">登录</a>


                    </div>
                {% endif %}
            </div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/12.PNG' %}"/></a>
                    <div class="searchbox fr">
{#                        <div class="selectContainer fl">#}
{#                            <span class="selectOption" id="jsSelectOption"#}
{#                                  {% ifequal  '/' request.path %}data-value="course"> 公开课{% endifequal %}#}
{#                                  {% ifequal  '/course' request.path|slice:":7" %}data-value="course">#}
{#                                      公开课 {% endifequal %}{% ifequal  '/org/teacher' request.path|slice:":12" %}#}
{#                                      data-value="teacher"> 授课教师{% endifequal %}#}
{#                                  {% ifequal  '/org/list' request.path|slice:":9" %}data-value="org">#}
{#                                      课程机构{% endifequal %}</span>#}
{#                            <ul class="selectMenu" id="jsSelectMenu">#}
{#                                <li data-value="course">公开课</li>#}
{#                                <li data-value="org">课程机构</li>#}
{#                                <li data-value="teacher">授课教师</li>#}
{#                            </ul>#}
{#                        </div>#}
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>

        </div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
{% endblock %}

<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
{#                <li class="logo"><a href="{% url 'index' %}"><img src="{% static 'images/13.PNG' %}"/></a></li>#}
{#                <li class="code"><img src="{% static 'images/code.jpg' %}"/>#}
{#                    <p class="center">扫描关注微信</p></li>#}
                <li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/>
                    <p class="tell">23333333</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>

        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">©2019 WHUT-废品回收系统 保留所有权利</span>
            <span class="fr">copyright© 2019 ICP备案证书号：<a style="color:#717171 " href="http://www.miitbeian.gov.cn/">陕ICP备16011333号-1</a></span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static '' %}js/plugins/laydate/laydate.js"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}" type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}" type="text/javascript"></script>
{% block custom_js %} {% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block titile %}
首页 | 废品回收系统
{% endblock %}

{% load staticfiles %}
<!--crumbs start-->
{% block custom_bread %}
{% endblock %}


{% block content %}
    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">

                            {% for banner in banners %}
                            <li>
                                    <a href="{{ banner.url }}">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
{% endfor %}

						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="{% static 'images/feature1.png' %}"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="{% static 'images/feature2.png' %}"/>
					<p class="center">信用保证</p>
				</li>
				<li class="feature3">
					<img class="pic" src="{% static 'images/feature3.png' %}"/>
					<p class="center">快捷方便</p>
				</li>
				<li class="feature4">
					<img class="pic" src="{% static 'images/feature4.png' %}"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html>

<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>废品回收系统登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/login.css">
</head>
<body>
<div class="dialog" id="jsDialog">
<!--提示弹出框-->
<div class="successbox dialogbox" id="jsSuccessTips">
    <h1>成功提交</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="cont">
        <h2>您的需求提交成功！</h2>
        <p></p>
    </div>
</div>

</div>
<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">废品回收系统平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>33333333</span></li>
                <li class="active"><a href="{% url 'user:login' %}">[登录]</a></li>
                <li><a href="{% url 'user:register' %}">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="index.html"></a>
                <h1>用户登录</h1>
                <a class="index-font" href="index.html">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">
                            <li><a href=""><img width="483" height="472" src="/static/images/16.png" /></a></li>
                            <li><a href=""><img width="483" height="472" src="/static/images/17.png" /></a></li>
                            <li><a href=""><img width="483" height="472" src="/static/images/18.jpg" /></a></li>
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <h2>帐号登录</h2>
                <form action="/user/login/" method="post" autocomplete="off">
                    <input type='hidden' name='csrfmiddlewaretoken' value='mymQDzHWl2REXIfPMg2mJaLqDfaS1sD5' />
                    <div class="form-group marb20 {% if login_form.errors.username %}errorput{% endif %} ">
                        <label>手&nbsp;机&nbsp;号</label>
                        <input name="username" id="account_l" type="text" placeholder="手机号" />
                    </div>
                    <div class="form-group marb8 {% if login_form.errors.password %}errorput{% endif %}">
                        <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                        <input name="password" id="password_l" type="password" placeholder="请输入您的密码" />
                    </div>
                    <div class="error btns login-form-tips" id="jsLoginTips">{{ msg }}</div>
                     <div class="auto-box marb38">
                        <a class="fr" href="{% url 'user:login' %}">忘记密码？</a>
                     </div>
                     <input class="btn btn-green" id="jsLoginBtn" type="submit" value="立即登录 > " />
                    {% csrf_token %}
                </form>
                <p class="form-p">没有帐号？<a href="register.html">[立即注册]</a></p>
            </div>
        </div>
    </div>
</section>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/login.js"  type="text/javascript"></script>
</body>
</html>

templates/order-list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block titile %}
    废品回收系统 | 废品种类
{% endblock %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="/index/">首页</a>></li>
                <li>订单列表</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
    <section>
        <div class="wp butler_list_box list">
            <div class='left'>
                <div class="butler_list layout">
                    <div class="head">
                        <ul class="fl tab_header">
                            {% ifequal request.user.role 1 %}
                                <li>订单列表</li>
                            {% endifequal %}
                            {% ifequal request.user.role 0 %}
                                <li id="order_create_btn" type="button">下单</li>
                                {% csrf_token %}
                            {% endifequal %}
                        </ul>
                    </div>
                    {#                     回收人员#}
                    {% ifequal request.user.role 1 %}
                        {% for order in orders.object_list %}
                            <dl class="des">
                                <dt>
                                    {% ifequal order.status 1 %}
                                        <a href="{% url 'order:order_submit' order.order_number %}">
                                            <span>提交订单</span>
                                        </a>
                                    {% endifequal %}
                                </dt>
                                <dd>
                                    <ul class="cont">
                                        <li>订单号：<span>{{ order.order_number }}</span></li>
                                        <li>顾客手机号：<span>{{ order.customer_phone }}&nbsp;</span></li>
                                        <li>顾客地址：<span>{{ order.customer_address }}</span></li>
                                        <li>订单状态：
                                            {% ifequal order.status 0 %}<span>未处理</span>{% endifequal %}
                                            {% ifequal order.status 1 %}<span>处理中</span>{% endifequal %}
                                            {% ifequal order.status 2 %}<span>处理完成</span>{% endifequal %}
                                        </li>
                                        <li>下单时间：<span>{{ order.time }}</span></li>
                                    </ul>
                                </dd>
                            </dl>
                        {% endfor %}
                    {% endifequal %}

                    {#                    // 社区人员#}
                    {% ifequal request.user.role 0 %}
                        {% for order in orders.object_list %}
                            <dl class="des">
                                <dt>
                                    {% ifequal order.status 1 %}
                                        <a href="{% url 'order:order_submit' order.order_number %}">
                                            <span>提交订单</span>
                                        </a>
                                    {% endifequal %}
                                </dt>
                                <dd>
                                    <ul class="cont">
                                        <li>订单号：<span>{{ order.order_number }}</span></li>
                                        <li>服务员手机号：<span>{{ order.waiter_phone }}</span></li>
                                        <li>订单金额：<span>{{ order.total_money }}&nbsp;</span></li>
                                        <li>下单时间：<span>{{ order.create_time }}</span></li>
                                        <li>订单状态：
                                            {% ifequal order.status 0 %}<span>未处理</span>{% endifequal %}
                                            {% ifequal order.status 1 %}<span>处理中</span>{% endifequal %}
                                            {% ifequal order.status 2 %}<span>处理完成</span>{% endifequal %}
                                        </li>
                                        <li>下单时间：<span>{{ order.time }}</span></li>
                                    </ul>
                                </dd>
                            </dl>
                        {% endfor %}
                    {% endifequal %}
                </div>
                <div class="pageturn">
                    <ul class="pagelist">
                        {% if orders.has_previous %}
                            <li class="long"><a href="?{{ orders.previous_page_number.querystring }}">上一页</a></li>
                        {% endif %}

                        {% for page in orders.pages %}
                            {% if page %}
                                {% ifequal page orders.number %}
                                    <li class="active"><a href="{{ page.querystring }}">{{ page }}</a></li>
                                {% else %}
                                    <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                                {% endifequal %}
                            {% else %}
                                <li class="none"><a href="">...</a></li>
                            {% endif %}
                        {% endfor %}
                        {% if orders.has_next %}
                            <li class="long"><a href="?{{ orders.next_page_number.querystring }}">下一页</a></li>
                        {% endif %}


                    </ul>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block custom_js %}
    <script>
        $(function () {
            $('#order_create_btn').on('click', function () {
                orderCreate();
            });
        });

        function orderCreate() {
            var token = $('input[name=csrfmiddlewaretoken]').val();
            $.ajax({
                cache: false,
                type: 'post',
                url: '/order/create/',
                data: {'csrfmiddlewaretoken': token },
                dataType: 'json',
                success: function (data) {
                    if (data.status === "success") {
                        alert(data.msg);
                    } else if (data.status === 'failure') {
                        alert(data.msg);
                    }
                }
            });
        }
    </script>
{% endblock %}

templates/register.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
    <title>废品回收系统注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body>
<div class="loginbox dialogbox">
    <h1>账号登录</h1>
    <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
    <div class="cont">
        <form id="jsLoginForm" autocomplete="off">
            <div class="box">
                <span class="word3">用户名</span>
                <input type="text" name="account_l" id="account_l" placeholder="手机号/邮箱" />
            </div>
            <div class="box">
                <span class="word2">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</span>
                <input type="password" name="password_l" id="password_l" placeholder="请输入您的密码"/>
            </div>
            <div class="error btns login-form-tips" id="jsLoginTips"></div> <!--登录错误提示-->
            <div class="btns">
                <span><input type="checkbox" id="jsAutoLogin" />&nbsp;自动登录</span>
                <span class="forget btn fr">忘记密码</span>
            </div>
            <div class="button">
                <input type="button" value="登录" id="jsLoginBtn" />
            </div>
            <div class="btns">
                <span class="fr">没有账号？<span class="regist btn">立即注册</span></span>
            </div>
        </form>
    </div>
</div>
<div class="dialog" id="jsDialog">
    <!--提示弹出框-->
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="/static/images/dig_close.png"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
</div>

<div class="bg" id="dialogBg"></div>
<header>
    <div class="c-box fff-box">
        <div class="wp header-box">
            <p class="fl hd-tips">废品回收系统平台！</p>
            <ul class="fr hd-bar">
                <li>服务电话：<span>4001008031</span></li>
                <li><a href="/user/login">[登录]</a></li>
                <li class="active"><a href="/user/register">[注册]</a></li>
            </ul>
        </div>
    </div>
</header>
<section>
    <div class="c-box bg-box">
        <div class="login-box clearfix">
            <div class="hd-login clearfix">
                <a class="index-logo" href="/index/"></a>
                <h1>用户注册</h1>
                <a class="index-font" href="/index/">回到首页</a>
            </div>
            <div class="fl slide">
                <div class="imgslide">
                    <ul class="imgs">

                        <li><a href=""><img width="483" height="472" src="/static/images/16.png" /></a></li>

                        <li><a href=""><img width="483" height="472" src="/static/images/17.png" /></a></li>

                        <li><a href=""><img width="483" height="472" src="/static/images/18.jpg" /></a></li>

                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
            <div class="fl form-box">
                <div class="tab">
                    <h2 class="active">手机注册</h2>
                </div>
                <div class="tab-form">
                    <form id="phone_register_form" method="post" action="{% url 'user:register' %}" autocomplete="off">
                        <input type='hidden' name='csrfmiddlewaretoken' value='gTZljXgnpvxn0fKZ1XkWrM1PrCGSjiCZ' />
                        <div class="form-group marb20 {% if register_form.errors.email %}errorput{% endif %}">
                            <label>手&nbsp;&nbsp;&nbsp;&nbsp;机&nbsp;</label>
                            <input  type="text" id="id_email" name="phone" value="{{ register_form.phone.value }}" placeholder="请输入您的手机号" />
                        </div>
                        <div class="form-group marb8 {% if register_form.errors.password %}errorput{% endif %}">
                            <label>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</label>
                            <input type="password" id="id_password" name="password"  value="{{ register_form.password.value }}" placeholder="请输入6-20位非中文字符密码" />
                        </div>
                        <div class="form-group marb8 captcha1 {% if register_form.errors.captcha %}errorput{% endif %}">
                            <label>验&nbsp;证&nbsp;码</label>
                            <input  type="text" id="id_captcha_0" name="code"
                                   placeholder="输入验证码"/>
                            <input class="getcode getting" type="button" id="id_captcha_1" value="获取验证码"/>
                        </div>
                        <div class="form-group marb8">
                            <label>身&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;份</label>

                            <label>&nbsp;&nbsp;<input type="radio" name="role" value="0"
                                                      checked="checked">社区人员</label>
                            <label>&nbsp;&nbsp;<input type="radio" name="role"
                                                            value="1"
                            >工作人员</label>
                        </div>
                        <div class="error btns" id="jsEmailTips">{% for key, error in register_form.errors.items %}{{ error }}{{ msg }}{% endfor %}
                        </div>
                        <div class="auto-box marb8">
                        </div>
                        <input class="btn btn-green" id="jsEmailRegBtn" type="submit" value="注册并登录" />
                        {% csrf_token %}
                    </form>
                </div>
                <p class="form-p">已有账号？<a href="{% url 'user:login' %}">[立即登录]</a></p>
            </div>
        </div>
    </div>
</section>

<input id="isLogin" type="hidden" value="False"/>
<script src="/static/js/jquery.min.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/validateDialog.js"  type="text/javascript"></script>
<script src="/static/js/login.js"  type="text/javascript"></script>

<script>
    $(function () {
        $('#id_captcha_1').on('click', function () {
            sendPhoneCode($(this))
        });
    });

    function sendPhoneCode($btn) {
        $.ajax({
            cache: false,
            type: "post",
            dataType: 'json',
            url: "/user/send_phone_code/",
            data: $('#phone_register_form').serialize(),
            async: true,
            beforeSend: function (XMLHttpRequest) {
                $btn.val("发送中...").show(3000);
                $btn.attr('disabled', true);
            },
            success: function (data) {
                if (data.email) {
                    Dml.fun.showValidateError($('#jsChangePhone'), data.email);
                } else if (data.status == "success") {
                    Dml.fun.showErrorTips($('#jsEmailTips'), "手机号成功");
                    setTimeout(function () {
                        location.reload();
                    }, 1000);
                } else {
                    Dml.fun.showValidateError($('#id_email'), "手机号失败");
                }
            }
        });
    }
</script>
</body>
</html>

templates/scrap-list.html
{% extends 'base.html' %}
{% block titile %}
废品回收系统 | 废品种类
{% endblock %}
{% block bread %}
    <section>
        <div class="wp">
            <ul class="crumbs">
                <li><a href="index.html">首页</a>></li>
                <li>废品种类</li>
            </ul>
        </div>
    </section>
{% endblock %}
{% block content %}
        <section>
	<div class="wp butler_list_box list">
	<div class='left'>
		<div class="butler_list layout">
			<div class="head">
				<ul class="fl tab_header">
					<li class="{% if sort == '' %}active{% endif %}"><a href="?sort=">废品种类</a> </li>
				</ul>
			</div>
                {% for scrap in scraps.object_list %}
                    <dl class="des">
                    <dd>
						<ul class="cont">
                            <li>商品名称：<span>{{ scrap.name }}</span></li>
							<li>商品单价：<span>{{ scrap.price }}</span></li>
						</ul>
					</dd>
                </dl>
                {% endfor %}
        </div>
        <div class="pageturn">
            <ul class="pagelist">
                {% if scraps.has_previous %}
                    <li class="long"><a href="?{{ scraps.previous_page_number.querystring }}">上一页</a></li>
                {% endif %}

                {% for page in scraps.pages %}
                    {% if page %}
                        {% ifequal page scraps.number %}
                            <li class="active"><a href="{{ page.querystring }}">{{ page }}</a></li>
                        {% else %}
                            <li><a href="?{{ page.querystring }}" class="page">{{ page }}</a></li>
                        {% endifequal %}
                    {% else %}
                        <li class="none"><a href="">...</a></li>
                    {% endif %}
                {% endfor %}
                {% if scraps.has_next %}
                    <li class="long"><a href="?{{ scraps.next_page_number.querystring }}">下一页</a></li>
                {% endif %}


            </ul>
        </div>
    </div>
    </div>
</section>
{% endblock %}